language: node_js

node_js: "12"

env: DATABASE_URL=postgresql://postgres@localhost:5432/greetingtest

before_script:
  - psql -c 'create database  greetingtest;' -U postgres
  - psql -U postgres -d greetingtest -a -f tables.sql

services:
  - postgresql